### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Rademoline** [InkCloudStarsDream/Rainworld-ModTranslation#6]
你们好！我最近正在做一个整合的大地图，包括原版+倾盆大雨+MOD区域，全部汉化并连接布局，目前已经连接了15个，汉化过程中使用的区域中文名主要都是来自这个模组翻译的MOD，**衷心感谢译者的付出**！！如果你们想看看这个大地图可以私聊加我qq（（不过不用担心，我这个整合地图无任何盈利方面的目的，纯因自己懒得翻MOD区域地图，就想着索性自己整合出来......在整合过程中我有一些建议如下：

1.目前The Grinder的小区域Crucible译为了坩埚，但根据环境特色和语境建议译为熔炉，也有朋友认为“锻造炉”很好

2.各大区域有名字的回响名我都自己低水平随便翻译了，可以参考一下，不知道用不用得上但是放这应该没事罢（
Far Shore（Eleven Bone Splinters, Buried Rivers）：十一尖骨，安葬百川
Chasing Wind（One Twig Upon A Silver Spindle）：银轴之上，一枝嫩芽
Lush Mire中的Serene Grotto（Over the Canopy,Thoughts Adrift）：树冠之上，思绪流浪

3.此mod暂未提供的Arid Barrens区域译名的建议：
Arid Barrens 旱漠
The Tower 高塔
The Dam 大坝（为了与Under Sea的The Dam水坝区分）

4.Gilded Sanctuary中的Tangled Steeple译为了蔓绕阶梯，但我没看懂为何这样译，于是自己译为了纠缠尖塔

**最后，以上都仅是一些建议，如果原译名有我未理解到位的更好的理由就请忽视我的建议啦——**

**Comment by InkCloudStarsDream** [comment]
The Dam和The Tower所对应的翻译只能存在一个，RW的翻译逻辑决定了不能针对不同的mod对同一个词予以不同的翻译，所以这个确实没办法。

**Comment by Exmeow** [comment]
Tangled Steeple子区域位于主区域下方，而“尖塔”一般表示的是处于地表之上的建筑。“蔓绕”是由于该子区域有藤蔓覆盖。

**Comment by Exmeow** [comment]
@InkCloudStarsDream 第一条是否修改，由你决定。

**Comment by InkCloudStarsDream** [comment]
好，Crucible更名为 锻造炉

**Comment by InkCloudStarsDream** [comment]
已更改

**Comment by Exmeow** [comment]
处理本issue的commit： ecd1298
