### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by Blank-Fei** [InkCloudStarsDream/Rainworld-ModTranslation#7]
1、矛师线SK的Shrouded Coast，现译为“遮蔽海岸”，改为“笼雾海滨”或“雾蔽海滨”。“雾”源自矛师线雾蒙蒙的环境，“海滨”我想对应“海滨设施”。
2、Reclaiming Entropy - A post-Saint world state的Smokestack Treetop，现译为“烟掩树梢”，改为“掩囱树林”。“掩囱”既指这里的树木掩蔽了烟囱，同时也与烟囱谐音，暗示这里曾经烟囱林立；“树林”虽然不符合原名的treetop，但我觉得符合这个区域的整体景观，同时我也想对应这片区域最开始也是一片树林。

目前看到的、想到的就这些了

**Comment by Exmeow** [comment]
我的翻译策略是信>达>雅。对于第二条，我表示反对，因为与原文表意差太多了。
@InkCloudStarsDream 等待你的意见。

**Comment by InkCloudStarsDream** [comment]
第一条，雾蔽或者雾笼这个确实可以
第二条，我也表示反对，对于烟囱顶棚我觉得你可能有一些误解，烟囱顶棚并非树林，所以没必要如此提示。

翻译的准确确实很有必要，比达和雅更为重要，否则在将来遇到类似的名称的mod后我们无法翻译以区别开。

**Comment by Exmeow** [comment]
已处理。
